import { Usuario, Post, SuggestionUser } from './types';

export const MOCK_USERS: Usuario[] = [
  {
    id: 'u-ana',
    nome: 'Ana Silva',
    email: 'ana.silva@fatec.sp.gov.br',
    tipo_usuario: 'aluno',
    foto_perfil: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    bio: 'Apaixonada por TypeScript, React e IA. Monitora de Algoritmos na Fatec.',
    curso: 'DSM - Desenv. Software Multiplataforma',
    criado_em: new Date().toISOString(),
    badges: [
      { id: 'b-monitor', nome: 'Monitor(a) Oficial', descricao: 'Monitor acadêmico selecionado da Fatec', cor_icone: '#B20000' },
      { id: 'b-hackathon', nome: 'Campeão Hackathon', descricao: 'Vencedor de Hackathon AgenTEC', cor_icone: '#D97706' },
    ],
  },
  {
    id: 'u-carlos',
    nome: 'Prof. Carlos Mendes',
    email: 'carlos.mendes@fatec.sp.gov.br',
    tipo_usuario: 'professor',
    foto_perfil: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    bio: 'Coordenador e pesquisador na Fatec. Focado em arquitetura em nuvem e inovação tecnológica.',
    curso: 'Gestão de TI',
    criado_em: new Date().toISOString(),
    badges: [
      { id: 'b-docente', nome: 'Docente Destaque', descricao: 'Professor com avaliação máxima e publicações', cor_icone: '#9333EA' },
    ],
  },
  {
    id: 'u-lucas',
    nome: 'Lucas Oliveira',
    email: 'lucas.oliveira@fatec.sp.gov.br',
    tipo_usuario: 'aluno',
    foto_perfil: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
    bio: 'Dev Full-Stack, competidor em maratonas de programação e entusiasta de Next.js.',
    curso: 'DSM - Desenv. Software Multiplataforma',
    criado_em: new Date().toISOString(),
    badges: [
      { id: 'b-hackathon', nome: 'Campeão Hackathon', descricao: 'Vencedor de Hackathon AgenTEC', cor_icone: '#D97706' },
    ],
  },
  {
    id: 'u-mariana',
    nome: 'Mariana Souza',
    email: 'mariana.souza@fatec.sp.gov.br',
    tipo_usuario: 'aluno',
    foto_perfil: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    bio: 'Líder discente, apaixonada por acessibilidade web, design system e comunidade Fatecana.',
    curso: 'ADS - Análise e Desenv. Sistemas',
    criado_em: new Date().toISOString(),
    badges: [
      { id: 'b-lider', nome: 'Líder Discente', descricao: 'Representante de turma eleito pelos pares', cor_icone: '#16A34A' },
      { id: 'b-ic', nome: 'Iniciação Científica', descricao: 'Pesquisador de Iniciação Científica do CPS', cor_icone: '#2563EB' },
    ],
  },
  {
    id: 'u-techlab',
    nome: 'TechLab Inovação CPS',
    email: 'contato@techlab.cps.sp.gov.br',
    tipo_usuario: 'empresa',
    foto_perfil: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150',
    bio: 'Hub de inovação e aceleração de carreiras tecnológicas para alunos do Centro Paula Souza.',
    curso: 'Parceiro Institucional',
    criado_em: new Date().toISOString(),
    badges: [],
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p-1',
    usuario_id: 'u-ana',
    conteudo: 'Muito animada com o lançamento da plataforma AgenTEC! 🐊 Redes acadêmicas conectando alunos e professores da Fatec de verdade. Quem mais aqui é do curso de DSM? #Fatec #AgenTEC #DSM',
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    total_curtidas: 14,
    total_comentarios: 3,
    curtido_pelo_usuario: false,
    autor: {
      id: 'u-ana',
      nome: 'Ana Silva',
      tipo_usuario: 'aluno',
      foto_perfil: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      curso: 'DSM - Desenv. Software Multiplataforma',
      badges: [
        { id: 'b-monitor', nome: 'Monitor(a) Oficial', descricao: 'Monitor acadêmico selecionado da Fatec', cor_icone: '#B20000' },
        { id: 'b-hackathon', nome: 'Campeão Hackathon', descricao: 'Vencedor de Hackathon AgenTEC', cor_icone: '#D97706' },
      ],
    },
  },
  {
    id: 'p-2',
    usuario_id: 'u-carlos',
    conteudo: 'Aviso aos alunos de Gestão de TI e DSM: as inscrições para os novos projetos de Iniciação Científica do CPS estão abertas até sexta-feira. Venham conversar comigo sobre os temas de Cloud e IA aplicada! #IniciaçãoCientifica #CPS #Fatec',
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    total_curtidas: 28,
    total_comentarios: 1,
    curtido_pelo_usuario: true,
    autor: {
      id: 'u-carlos',
      nome: 'Prof. Carlos Mendes',
      tipo_usuario: 'professor',
      foto_perfil: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      curso: 'Gestão de TI',
      badges: [
        { id: 'b-docente', nome: 'Docente Destaque', descricao: 'Professor com avaliação máxima e publicações', cor_icone: '#9333EA' },
      ],
    },
  },
  {
    id: 'p-3',
    usuario_id: 'u-lucas',
    conteudo: 'Galera, estamos montando uma equipe para o próximo Hackathon Inter-Fatecs! Precisamos de mais um dev focado em front-end com Next.js e Tailwind. Mandem mensagem aqui nos comentários! 🚀 #HackathonFatec #DevCommunity',
    criado_em: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    total_curtidas: 19,
    total_comentarios: 2,
    curtido_pelo_usuario: false,
    autor: {
      id: 'u-lucas',
      nome: 'Lucas Oliveira',
      tipo_usuario: 'aluno',
      foto_perfil: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
      curso: 'DSM - Desenv. Software Multiplataforma',
      badges: [
        { id: 'b-hackathon', nome: 'Campeão Hackathon', descricao: 'Vencedor de Hackathon AgenTEC', cor_icone: '#D97706' },
      ],
    },
  },
  {
    id: 'p-4',
    usuario_id: 'u-techlab',
    conteudo: 'Vaga de Estágio em Desenvolvimento de Software aberta exclusivamente para alunos da Fatec no TechLab CPS! Benefícios atrativos, bolsa auxílio e mentoria com engenheiros sêniores. Link no nosso perfil institucional. #VagasEstagio #EstagioTech',
    criado_em: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    total_curtidas: 35,
    total_comentarios: 0,
    curtido_pelo_usuario: true,
    autor: {
      id: 'u-techlab',
      nome: 'TechLab Inovação CPS',
      tipo_usuario: 'empresa',
      foto_perfil: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150',
      curso: 'Parceiro Institucional',
      badges: [],
    },
  },
];

export const MOCK_SUGGESTIONS: SuggestionUser[] = [
  {
    id: 'u-carlos',
    nome: 'Prof. Carlos Mendes',
    tipo_usuario: 'professor',
    foto_perfil: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    curso: 'Gestão de TI',
    bio: 'Coordenador e pesquisador na Fatec.',
    badges: [{ id: 'b-docente', nome: 'Docente Destaque', descricao: '', cor_icone: '#9333EA' }],
    seguindo: true,
  },
  {
    id: 'u-lucas',
    nome: 'Lucas Oliveira',
    tipo_usuario: 'aluno',
    foto_perfil: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
    curso: 'DSM',
    bio: 'Dev Full-Stack.',
    badges: [{ id: 'b-hackathon', nome: 'Campeão Hackathon', descricao: '', cor_icone: '#D97706' }],
    seguindo: true,
  },
  {
    id: 'u-mariana',
    nome: 'Mariana Souza',
    tipo_usuario: 'aluno',
    foto_perfil: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    curso: 'ADS',
    bio: 'Líder de turma.',
    badges: [{ id: 'b-lider', nome: 'Líder Discente', descricao: '', cor_icone: '#16A34A' }],
    seguindo: false,
  },
  {
    id: 'u-techlab',
    nome: 'TechLab Inovação CPS',
    tipo_usuario: 'empresa',
    foto_perfil: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150',
    curso: 'Parceiro Institucional',
    bio: 'Hub de inovação.',
    badges: [],
    seguindo: false,
  },
];
